# server/app.py
"""
FastAPI server for CredLess-Env.
Uses a SINGLE shared environment instance so state persists
between /reset and /step HTTP calls.
"""
import json
import subprocess
from fastapi import FastAPI, HTTPException
from fastapi.responses import JSONResponse
from pydantic import BaseModel
from typing import Optional

from models import CreditAction, CreditObservation
from server.environment import CreditAnalystEnvironment
from server.tasks import TASK_REGISTRY
from server.data_generator import FIELD_RANGES

# ── Single shared environment instance ────────────────────────────────────────
env = CreditAnalystEnvironment()

app = FastAPI(
    title="CredLess-Env",
    description="OpenEnv RL environment for alternative credit scoring.",
    version="1.0.0",
)


# ── Request body models ───────────────────────────────────────────────────────
class ResetRequest(BaseModel):
    task_name: str = "binary_decision"
    seed: Optional[int] = None


# ── Standard OpenEnv endpoints ────────────────────────────────────────────────
@app.get("/health")
def health():
    return {"status": "healthy"}


@app.post("/reset")
def reset(body: ResetRequest = ResetRequest()):
    obs = env.reset(task_name=body.task_name, seed=body.seed)
    return {"observation": obs.dict()}


@app.post("/step")
def step(action: CreditAction):
    obs = env.step(action)
    return {"observation": obs.dict()}


@app.get("/state")
def state():
    s = env.state
    return {
        "episode_id":        s.episode_id,
        "task_name":         s.task_name,
        "step_count":        s.step_count,
        "cumulative_reward": s.cumulative_reward,
        "fields_requested":  s.fields_requested,
    }


# ── Hackathon-required extra endpoints ────────────────────────────────────────
@app.get("/tasks")
def list_tasks():
    return {"tasks": TASK_REGISTRY}


@app.get("/grader")
def grader_info():
    s = env.state
    return {
        "episode_id":        s.episode_id,
        "task_name":         s.task_name,
        "steps_taken":       s.step_count,
        "cumulative_reward": round(s.cumulative_reward, 4),
        "fields_requested":  s.fields_requested,
        "note":              "episode_score is in the observation when done=True",
    }


@app.get("/baseline")
def run_baseline():
    try:
        result = subprocess.run(
            ["python", "baseline.py", "--output-json"],
            capture_output=True, text=True, timeout=300,
        )
        scores = json.loads(result.stdout)
    except json.JSONDecodeError:
        scores = {"error": "Parse failed", "stderr": result.stderr}
    except subprocess.TimeoutExpired:
        scores = {"error": "Timed out"}
    except Exception as exc:
        scores = {"error": str(exc)}
    return JSONResponse(content=scores)

def main():
    import uvicorn
    uvicorn.run(
        "server.app:app",
        host="0.0.0.0",
        port=8000,
        workers=2,
    )


if __name__ == "__main__":
    main()


# ── OpenAPI / docs auto-generated by FastAPI at /docs ─────────────────────────